version: '3.8'
services:
  backend:
    build: ./backend
    image: union_backend_web
    command: python manage.py runserver 0.0.0.0:8000

    container_name: django
    volumes: 
      - ./backend:/app

    ports:
      - "8000:8000"

    environment:
      - "DEBUG=1"
      - "SECRET_KEY=django-insecure-6&ac#p@km0q$$to%w9_9#en1p5sggut!r+$$z#l-+o*!-12ny*6@"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"
      - "PRODUCTION=0"

    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    container_name: postgresql
    environment:
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  redis:
    container_name: redis
    image: redis:6.2.3

  frontend:
    build: ./frontend
    image: union_frontend_web
    command: npm start
    container_name: react

    volumes:
      - ./frontend:/frontend

    ports:
      - "9000:9000"

    stdin_open: true # docker run -i
    tty: true # docker run -t

volumes:
  postgres_data: