# Generated by Django 3.2 on 2021-05-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='vova', max_length=255, verbose_name='First name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='the best', max_length=255, verbose_name='Last name'),
            preserve_default=False,
        ),
    ]
