# Generated by Django 3.2 on 2021-06-08 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210530_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('friends', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('main_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='friends_obj', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
