# Generated by Django 3.2 on 2021-07-06 21:35

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_invitetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='invitetoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 21, 34, 56, 286521)),
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
