# Generated by Django 3.2 on 2021-07-06 21:35

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210706_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitetoken',
            name='expired_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 7, 21, 35, 14, 850584)),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
